name: Build and test OpenVR driver

on: [ push, pull_request, workflow_dispatch ]

jobs:
  setup-matrix:
    name: Setup build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - id: setup-matrix
        shell: bash
        run: |
          cat <<EOF | jq -c > matrix.json
          {
            "include": [
              {"os": "windows-2025", "name": "win64"},
              {"os": "ubuntu-latest", "name": "x64-linux"},
              {"os": "ubuntu-24.04-arm", "name": "aarch64-linux"}
            ]
          }
          EOF
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ matrix.os }})
    needs: [setup-matrix]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    env:
      # Indicates the CMake build directory where project files and binaries are being produced.
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Get submodule commit hashes
      id: get-submodule-commit-hashes
      run: git submodule foreach --recursive git rev-parse HEAD > submodule-hashes.txt

    - name: Generate cache key
      id: gen-cache-key
      shell: bash
      run: |
        echo "cache-key=${{ matrix.os }}-${{ hashFiles('submodule-hashes.txt') }}-${{ hashFiles('CMakeLists.txt') }}" >> $GITHUB_OUTPUT

    - name: Set up CPM cache
      id: setup-cpm-cache
      uses: actions/cache@v5
      with:
        path: ~/cpm-cache
        key: cpm-${{ steps.gen-cache-key.outputs.cache-key }}
        restore-keys: |
          cpm-${{ matrix.os }}-

    - name: Set up sccache
      uses: hendrikmuhs/ccache-action@v1.2
      id: setup-ccache
      with:
        key: ${{ steps.gen-cache-key.outputs.cache-key }}
        variant: sccache
        append-timestamp: false
        restore-keys: |
          ${{ matrix.os }}-

    - if: matrix.os == 'windows-2025'
      name: Configure and build on Windows
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" -G Ninja ^
          -DCPM_SOURCE_CACHE=%USERPROFILE%\cpm-cache                                ^
          -DCMAKE_C_COMPILER_LAUNCHER=sccache                                       ^
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache                                     ^
          -DSLIMEVR_BUILD_TESTS=ON                                                  ^
          -DCMAKE_BUILD_TYPE=Release
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Release -j6

    - if: matrix.os != 'windows-2025'
      name: Configure and build on Unix
      run: |
        cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" -G Ninja \
          -DCPM_SOURCE_CACHE=~/cpm-cache                                            \
          -DCMAKE_C_COMPILER_LAUNCHER=sccache                                       \
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache                                     \
          -DSLIMEVR_BUILD_TESTS=ON                                                  \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Release -j6

    - name: Upload driver
      uses: actions/upload-artifact@v7
      with:
        name: slimevr-openvr-driver-${{ matrix.name }}
        path: ${{ env.CMAKE_BUILD_DIR }}/driver

    - name: Upload tests
      uses: actions/upload-artifact@v7
      with:
        name: tests-${{ matrix.name }}
        path: ${{ env.CMAKE_BUILD_DIR }}/tests*
  
  test:
    name: Run tests (${{ matrix.os }})
    needs: [setup-matrix, build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: tests-${{ matrix.name }}
          path: ${{ github.workspace }}
      - if: matrix.os == 'windows-2025'
        name: Run tests on Windows
        working-directory: ${{ github.workspace }}/
        run: .\tests.exe
      - if: matrix.os != 'windows-2025'
        name: Run tests on Unix
        working-directory: ${{ github.workspace }}/
        run: chmod +x ./tests && ./tests

  upload-release:
    name: Upload draft release
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download driver artifacts
        uses: actions/download-artifact@v8
        with:
          path: ${{ github.workspace }}
          pattern: slimevr-openvr-driver-*
          merge-multiple: true
          skip-decompress: true

      - uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          files: slimevr-openvr-driver-*.zip
